const c=document.querySelector('#view'),g=c.getContext('webgl',{antialias:true,alpha:false});if(!g)throw Error('WebGL unavailable');
const $=id=>document.getElementById(id),PI=Math.PI;
const V=(x=0,y=0,z=0)=>[x,y,z],add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>mul(a,1/(Math.hypot(...a)||1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function mm(a,b){let o=new Float32Array(16);for(let r=0;r<4;r++)for(let col=0;col<4;col++)o[col*4+r]=a[r]*b[col*4]+a[4+r]*b[col*4+1]+a[8+r]*b[col*4+2]+a[12+r]*b[col*4+3];return o}
function persp(f,a,n,z){let q=1/Math.tan(f/2),d=1/(n-z);return[q/a,0,0,0,0,q,0,0,0,0,(z+n)*d,-1,0,0,2*z*n*d,0]}
function look(e,t,u){let z=norm(sub(e,t)),x=norm(cross(u,z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]}
function model(p,s,r=[0,0,0]){let[x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);let m=[cy*cz,cy*sz,-sy,0,sx*sy*cz-cx*sz,sx*sy*sz+cx*cz,sx*cy,0,cx*sy*cz+sx*sz,cx*sy*sz-sx*cz,cx*cy,0,0,0,0,1];m[0]*=s[0];m[1]*=s[0];m[2]*=s[0];m[4]*=s[1];m[5]*=s[1];m[6]*=s[1];m[8]*=s[2];m[9]*=s[2];m[10]*=s[2];m[12]=p[0];m[13]=p[1];m[14]=p[2];return m}
const VS=`attribute vec3 p,n;uniform mat4 mvp,mod;uniform vec3 color,light;varying vec3 C;varying float L;void main(){C=color;L=.3+.7*max(dot(normalize((mod*vec4(n,0.)).xyz),normalize(light)),0.);gl_Position=mvp*vec4(p,1.);}`,FS=`precision mediump float;varying vec3 C;varying float L;uniform float alpha;void main(){gl_FragColor=vec4(C*L,alpha);}`;
function sh(t,s){let q=g.createShader(t);g.shaderSource(q,s);g.compileShader(q);if(!g.getShaderParameter(q,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(q));return q}let P=g.createProgram();g.attachShader(P,sh(g.VERTEX_SHADER,VS));g.attachShader(P,sh(g.FRAGMENT_SHADER,FS));g.linkProgram(P);if(!g.getProgramParameter(P,g.LINK_STATUS))throw Error('shader link');
const L={p:g.getAttribLocation(P,'p'),n:g.getAttribLocation(P,'n'),mvp:g.getUniformLocation(P,'mvp'),mod:g.getUniformLocation(P,'mod'),color:g.getUniformLocation(P,'color'),light:g.getUniformLocation(P,'light'),alpha:g.getUniformLocation(P,'alpha')};
function mesh(a){let b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(a),g.STATIC_DRAW);return{b,count:a.length/6}}
function cube(){let a=[];for(let[n,A,B,C,D]of[[[0,0,1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],[[0,0,-1],[1,-1,-1],[-1,-1,-1],[-1,1,-1],[1,1,-1]],[[1,0,0],[1,-1,1],[1,-1,-1],[1,1,-1],[1,1,1]],[[-1,0,0],[-1,-1,-1],[-1,-1,1],[-1,1,1],[-1,1,-1]],[[0,1,0],[-1,1,1],[1,1,1],[1,1,-1],[-1,1,-1]],[[0,-1,0],[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1]])])for(let t of[[A,B,C],[A,C,D]])for(let q of t)a.push(...q,...n);return mesh(a)}
function jet(){let a=[];const add=(A,B,C,n)=>a.push(...A,...n,...B,...n,...C,...n),q=[[-1,0,-3],[1,0,-3],[0,0,4],[-1,0,-1],[-5,0,1],[0,0,-1],[1,0,-1],[5,0,1],[0,0,-1],[-.5,0,1],[.5,0,1],[0,1,2],[0,0,-3],[0,1,0],[0,0,4],[0,-1,1],[0,0,4],[0,-1,1]];add(q[0],q[1],q[2],[0,0,-1]);add(q[3],q[4],q[5],[0,1,0]);add(q[6],q[7],q[8],[0,1,0]);add(q[9],q[10],q[11],[0,1,0]);return mesh(a)}const CUBE=cube(),JET=jet();
const s={p:[0,110,0],yaw:0,pitch:-.03,roll:0,speed:215,hp:100,ammo:120,lock:-1,boost:0};const E=[-1,0,1].map(i=>({p:[i*95,100+i*18,-500-i*280],hp:100,t:i*2})),shots=[],ms=[];
const keys=new Set,inp={p:0,r:0};let live=false,last=0;
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space')s.boost=1;if(e.key.toLowerCase()==='f')fire()});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.code==='Space')s.boost=0});
function fire(){if(!live||!s.ammo)return;s.ammo--;shots.push({p:[...s.p],life:.18});$('ammo').textContent=s.ammo;$('weapon').textContent='FIRING';setTimeout(()=>live&&($('weapon').textContent='READY'),120)}
function missile(){let e=E[s.lock];if(!live||!e||e.hp<=0)return;ms.push({p:[...s.p],e,life:3});$('comms').textContent='AWACS // FOX-2 AWAY'}
function start(){live=true;$('boot').style.display='none';$('game').hidden=false;resize();last=performance.now();requestAnimationFrame(loop)}$('start').onclick=start;$('fire').onclick=fire;$('missile').onclick=missile;
c.addEventListener('mousemove',e=>{if(live){s.yaw-=e.movementX*.0015;s.pitch=clamp(s.pitch-e.movementY*.001,-.75,.75)}});c.addEventListener('mousedown',e=>e.button===0&&fire());
let sid=null;$('stick').onpointerdown=e=>{sid=e.pointerId;$('stick').setPointerCapture(sid);stick(e)};$('stick').onpointermove=e=>sid===e.pointerId&&stick(e);$('stick').onpointerup=$('stick').onpointercancel=()=>{sid=null;inp.p=inp.r=0;$('stick').firstElementChild.style.transform=''};function stick(e){let r=$('stick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=48,d=Math.hypot(x,y),k=d>m?m/d:1;x*=k;y*=k;inp.r=x/m;inp.p=-y/m;$('stick').firstElementChild.style.transform=`translate(${x}px,${y}px)`}
let lid=null,lx=0;$('look').onpointerdown=e=>{lid=e.pointerId;lx=e.clientX;$('look').setPointerCapture(lid)};$('look').onpointermove=e=>{if(e.pointerId===lid){s.yaw-=(e.clientX-lx)*.008;lx=e.clientX}};$('look').onpointerup=$('look').onpointercancel=()=>lid=null;
function update(dt){let p=0,r=0;if(keys.has('w'))p=1;if(keys.has('s'))p=-1;if(keys.has('a'))r=-1;if(keys.has('d'))r=1;if(Math.abs(inp.p)>.05)p=inp.p;if(Math.abs(inp.r)>.05)r=inp.r;s.pitch=clamp(s.pitch+p*dt*.7,-.75,.75);s.roll+=(r-s.roll)*dt*3;s.yaw+=Math.sin(s.roll)*dt*.55;let f=[Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),-Math.cos(s.yaw)*Math.cos(s.pitch)],v=s.speed+(s.boost?105:0);s.p=add(s.p,mul(f,v*dt));s.p[1]=clamp(s.p[1],45,500);
E.forEach(e=>{if(e.hp<=0)return;e.t+=dt;let d=sub(s.p,e.p),dir=norm(d);e.p=add(e.p,mul(dir,65*dt));e.p[0]+=Math.sin(e.t*1.7)*dt*20});let best=-1,bd=1e9;E.forEach((e,i)=>{if(e.hp>0){let d=Math.hypot(...sub(e.p,s.p));if(d<bd&&d<750){bd=d;best=i}}});s.lock=best;$('lock').textContent=best>=0?'LOCK // BANDIT '+(best+1).toString().padStart(2,'0'):'NO LOCK';$('status').textContent=E.filter(e=>e.hp>0).length+' HOSTILES REMAIN';
ms.forEach((m,i)=>{if(!m.e||m.e.hp<=0){ms.splice(i,1);return}let d=norm(sub(m.e.p,m.p));m.p=add(m.p,mul(d,310*dt));m.life-=dt;if(m.life<=0||Math.hypot(...sub(m.e.p,m.p))<24){m.e.hp=0;ms.splice(i,1);$('comms').textContent='AWACS // DIRECT HIT'}});shots.forEach((x,i)=>{x.life-=dt;if(x.life<=0)shots.splice(i,1)});$('spd').textContent=Math.round(v*1.94);$('alt').textContent=Math.round(s.p[1]*3.28);drawRadar()}
function drawRadar(){let q=$('radar'),x=q.getContext('2d'),w=q.width=q.clientWidth*2,h=q.height=q.clientHeight*2;x.clearRect(0,0,w,h);x.strokeStyle='#65e7ff33';x.beginPath();x.arc(w/2,h/2,w*.38,0,2*PI);x.stroke();E.forEach(e=>{if(e.hp<=0)return;let d=sub(e.p,s.p);x.fillStyle='#ff5364';x.fillRect(w/2+clamp(d[0]/700,-1,1)*w*.4-2,h/2+clamp(d[2]/700,-1,1)*h*.4-2,4,4)})}
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;g.viewport(0,0,c.width,c.height)}addEventListener('resize',resize);
function draw(M,S,col,a=1,MESH=CUBE){g.bindBuffer(g.ARRAY_BUFFER,MESH.b);g.enableVertexAttribArray(L.p);g.vertexAttribPointer(L.p,3,g.FLOAT,false,24,0);g.enableVertexAttribArray(L.n);g.vertexAttribPointer(L.n,3,g.FLOAT,false,24,12);g.uniformMatrix4fv(L.mvp,false,M);g.uniformMatrix4fv(L.mod,false,S);g.uniform3fv(L.color,col);g.uniform1f(L.alpha,a);g.drawArrays(g.TRIANGLES,0,MESH.count)}
function render(){let f=[Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),-Math.cos(s.yaw)*Math.cos(s.pitch)],eye=add(s.p,mul(f,-28)),vp=mm(persp(PI/3,c.width/c.height,.5,5000),look(eye,add(s.p,mul(f,100)),[0,1,0]));g.clearColor(.01,.025,.045,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.useProgram(P);g.uniform3f(L.light,-.5,1,.3);
for(let x=-1200;x<=1200;x+=120)for(let z=-2200;z<=800;z+=120){let h=8+Math.sin(x*.009+z*.005)*6+Math.cos(z*.012)*4,m=model([x,h-20,z],[60,h,60]);draw(mm(vp,m),m,[.06,.16,.18])}
E.forEach((e,i)=>{if(e.hp<=0)return;let d=sub(s.p,e.p),r=Math.atan2(d[0],-d[2]),m=model(e.p,[9,3,18],[0,r,0]);draw(mm(vp,m),m,[.25,.28,.3],1,JET);if(i===s.lock){let q=model(e.p,[13,4,22],[0,r,0]);draw(mm(vp,q),q,[.8,.08,.05],.18)}});
let jm=model(s.p,[10,3,20],[s.pitch,s.yaw,s.roll]);draw(mm(vp,jm),jm,[.2,.27,.25],1,JET);shots.forEach(x=>{let m=model(x.p,[.5,.5,18],[s.pitch,s.yaw,s.roll]);draw(mm(vp,m),m,[1,.45,.05])});ms.forEach(x=>{let m=model(x.p,[1,1,5]);draw(mm(vp,m),m,[.8,.85,.9])})}
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;if(live){update(dt);render()}requestAnimationFrame(loop)}resize();window.__tidebreakerReady=true;