const eras={
  normandy:{name:'Normandy 1944',subtitle:'Allied advance • dawn assault',sky:'#7c8b91',ground:'#3e4a39',wall:'#59634c',enemy:'#6e4735',accent:'#e7c66b'},
  roman:{name:'Rome • 79 CE',subtitle:'Forum defense • volcanic dusk',sky:'#8d7561',ground:'#51483d',wall:'#7b6b58',enemy:'#9b5d42',accent:'#e0b46a'},
  frontier:{name:'American Frontier • 1876',subtitle:'Frontier town • high noon',sky:'#79a5c5',ground:'#92764c',wall:'#735b40',enemy:'#5a3c2d',accent:'#d7a64d'},
  future:{name:'New Arcadia • 2149',subtitle:'Neon district • containment breach',sky:'#17263b',ground:'#18232c',wall:'#29465a',enemy:'#a43f68',accent:'#53d8ff'}
};
const app=document.querySelector('#app');
app.innerHTML=`<div id="game"><canvas id="view"></canvas><div class="hud"><div class="top"><div><b id="eraName"></b><span id="subtitle"></span></div><div class="stats"><span>HEALTH <b id="health">100</b></span><span>SCORE <b id="score">0</b></span><span>WAVE <b id="wave">1</b></span></div></div><div id="objective">OBJECTIVE: Eliminate hostile targets</div><div class="crosshair">+</div><div class="bottom"><div class="hint">WASD move · Mouse look · Click fire · R reload · 1–4 era</div><div id="weapon">SIDEARM <span>12 / 12</span></div></div><div id="menu"><div class="panel"><div class="eyebrow">FIRST-PERSON HISTORICAL SIMULATION</div><h1>EPIC FPS<br><em>HISTORICAL ERAS</em></h1><p>Fight through original battlefields inspired by different eras. Fast, readable, replayable.</p><div class="era-grid">${Object.entries(eras).map(([k,e],i)=>`<button data-era="${k}"><kbd>${i+1}</kbd>${e.name}<small>${e.subtitle}</small></button>`).join('')}</div><button id="start">ENTER BATTLE</button><small class="legal">Original fictional game. Historical settings are stylized and non-documentary.</small></div></div></div></div>`;

const canvas=document.querySelector('#view'),ctx=canvas.getContext('2d'); let W,H,dpr; const keys=new Set();
let eraKey='normandy',running=false,health=100,score=0,wave=1,ammo=12,reloading=false,last=performance.now(),shotFlash=0,damageFlash=0,spawnTimer=0;
const player={x:0,y:0,a:0}; let enemies=[];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
function setEra(k){eraKey=k;document.documentElement.style.setProperty('--accent',eras[k].accent);document.querySelector('#eraName').textContent=eras[k].name;document.querySelector('#subtitle').textContent=eras[k].subtitle;reset()}
function reset(){player.x=0;player.y=0;player.a=0;health=100;score=0;wave=1;ammo=12;enemies=[];spawnTimer=0;for(let i=0;i<4;i++)spawn();updateHud()}
function spawn(){const ang=Math.random()*Math.PI*2,dist=5+Math.random()*7;enemies.push({x:Math.cos(ang)*dist,y:Math.sin(ang)*dist,hp:1,r:.28,cool:.5+Math.random()*.8})}
function updateHud(){document.querySelector('#health').textContent=Math.max(0,Math.round(health));document.querySelector('#score').textContent=score;document.querySelector('#wave').textContent=wave;document.querySelector('#weapon').innerHTML=`SIDEARM <span>${ammo} / 12</span>`}
function cast(ox,oy,a,max=30){let x=ox,y=oy,dx=Math.cos(a),dy=Math.sin(a);for(let t=0;t<max;t+=.05){x+=dx*.05;y+=dy*.05;if(Math.abs(x)>12||Math.abs(y)>12)return null;for(const e of enemies)if((e.x-x)**2+(e.y-y)**2<e.r**2)return e}return null}
function shoot(){if(!running||reloading||ammo<=0)return;if(document.pointerLockElement!==canvas)canvas.requestPointerLock();ammo--;shotFlash=.08;const e=cast(player.x,player.y,player.a);if(e){e.hp--;score+=100;if(e.hp<=0){enemies=enemies.filter(x=>x!==e);score+=100}}if(ammo===0)reload();updateHud()}
function reload(){if(reloading||ammo===12)return;reloading=true;setTimeout(()=>{ammo=12;reloading=false;updateHud()},750)}
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='r')reload();if(['1','2','3','4'].includes(e.key)){setEra(['normandy','roman','frontier','future'][+e.key-1])}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('mousedown',e=>{if(e.button===0)shoot()});canvas.addEventListener('click',()=>{if(running)canvas.requestPointerLock()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&running)player.a+=e.movementX*.0025});
document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{setEra(b.dataset.era);running=true;document.querySelector('#menu').classList.add('hidden');canvas.requestPointerLock()});document.querySelector('#start').onclick=()=>{running=true;document.querySelector('#menu').classList.add('hidden');canvas.requestPointerLock()};
function update(dt){if(!running)return;let s=3.4*dt,turn=(keys.has('arrowleft')?-1:0)+(keys.has('arrowright')?1:0);player.a+=turn*1.8*dt;let fx=Math.cos(player.a),fy=Math.sin(player.a),rx=-fy,ry=fx;if(keys.has('w')){player.x+=fx*s;player.y+=fy*s}if(keys.has('s')){player.x-=fx*s;player.y-=fy*s}if(keys.has('a')){player.x-=rx*s;player.y-=ry*s}if(keys.has('d')){player.x+=rx*s;player.y+=ry*s}player.x=Math.max(-11,Math.min(11,player.x));player.y=Math.max(-11,Math.min(11,player.y));spawnTimer+=dt;if(spawnTimer>3&&enemies.length<3+wave){spawn();spawnTimer=0}for(const e of enemies){const dx=player.x-e.x,dy=player.y-e.y,dist=Math.hypot(dx,dy);if(dist>1.8){e.x+=dx/dist*dt*.45;e.y+=dy/dist*dt*.45}else{e.cool-=dt;if(e.cool<=0){health-=8;e.cool=1.2;damageFlash=.18;if(health<=0){health=100;score=Math.max(0,score-250);wave=1;enemies=[];for(let i=0;i<4;i++)spawn()}}}}if(score>=wave*1000){wave++;for(let i=0;i<wave;i++)spawn()}shotFlash=Math.max(0,shotFlash-dt);damageFlash=Math.max(0,damageFlash-dt);updateHud()}
function render(){const e=eras[eraKey];ctx.fillStyle=e.sky;ctx.fillRect(0,0,W,H*.52);ctx.fillStyle=e.ground;ctx.fillRect(0,H*.52,W,H*.48);ctx.fillStyle=e.wall;for(let i=0;i<14;i++){let x=(i*97+(player.a*80)%97)-30;ctx.fillRect(x,H*.46,55,30)}
const fov=Math.PI/3;const sorted=enemies.map(x=>({...x,dist:Math.hypot(x.x-player.x,x.y-player.y),ang:Math.atan2(x.y-player.y,x.x-player.x)-player.a})).filter(o=>Math.abs(Math.atan2(Math.sin(o.ang),Math.cos(o.ang)))<fov/2+.2).sort((a,b)=>b.dist-a.dist);
for(const o of sorted){let a=Math.atan2(Math.sin(o.ang),Math.cos(o.ang));let sx=W/2+a/(fov/2)*(W/2),size=Math.min(H*1.1,H/(o.dist*.52)),y=H*.52-size*.55;ctx.fillStyle=e.enemy;ctx.fillRect(sx-size*.18,y+size*.18,size*.36,size*.58);ctx.fillStyle='#1a1412';ctx.fillRect(sx-size*.12,y,size*.24,size*.22);ctx.fillStyle=e.accent;ctx.fillRect(sx-size*.16,y+size*.28,size*.32,Math.max(3,size*.06))}
ctx.fillStyle='rgba(0,0,0,.25)';ctx.fillRect(0,0,W,70);if(shotFlash){ctx.fillStyle='rgba(255,220,120,.35)';ctx.beginPath();ctx.arc(W/2,H*.78,90,0,Math.PI*2);ctx.fill()}if(damageFlash){ctx.fillStyle='rgba(210,30,30,.28)';ctx.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)} setEra(eraKey);requestAnimationFrame(loop);
